<a href="https://colab.research.google.com/github/luanaketerlly/sales-data-analysis/blob/main/Tratamento_dataset_vendas_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Análise Comercial - Financial Dataset
**Objetivo:**  
*   Analisar o desempenho de vendas
*   Onde a empresa mais vende
*   Onde mais lucra
*   Onde está perdendo margem
*   O impacto dos descontos
*   Quais produtos e segmentos são mais estratégicos
*   Como o desempenho evolui ao longo do tempo







**Descrição do dataset:**  
O dataset contém informações de vendas, produtos, unidades vendidas, descontos, lucros e datas de transação.

#Documentação de projeto


[Clique aqui para abrir o PDF com resumo sobre o Dataset](https://drive.google.com/file/d/1Satg7MCapRGK4G9A2w0VmBhAGzlQz_as/view?usp=drive_link)

#Importação de bibliotecas / arquivo

In [188]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.pyplot as plt
import seaborn as sns
#Configurações gráficas
sns.set_style('whitegrid')
%matplotlib inline

In [189]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [190]:
df = pd.read_csv('/content/drive/MyDrive/Projeto-analise-vendas/data/dataset_original.csv')

##Checagem de Dataset

In [191]:
df.head()

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,None,"$1,618.50",$3.00,$20.00,"$32,370.00",$-,"$32,370.00","$16,185.00","$16,185.00",01/01/2014,1,January,2014
1,Government,Germany,Carretera,None,"$1,321.00",$3.00,$20.00,"$26,420.00",$-,"$26,420.00","$13,210.00","$13,210.00",01/01/2014,1,January,2014
2,Midmarket,France,Carretera,None,"$2,178.00",$3.00,$15.00,"$32,670.00",$-,"$32,670.00","$21,780.00","$10,890.00",01/06/2014,6,June,2014
3,Midmarket,Germany,Carretera,None,$888.00,$3.00,$15.00,"$13,320.00",$-,"$13,320.00","$8,880.00","$4,440.00",01/06/2014,6,June,2014
4,Midmarket,Mexico,Carretera,None,"$2,470.00",$3.00,$15.00,"$37,050.00",$-,"$37,050.00","$24,700.00","$12,350.00",01/06/2014,6,June,2014

In [192]:
df.columns

Index(['Segment', 'Country', ' Product ', ' Discount Band ', ' Units Sold ',
       ' Manufacturing Price ', ' Sale Price ', ' Gross Sales ', ' Discounts ',
       '  Sales ', ' COGS ', ' Profit ', 'Date', 'Month Number',
       ' Month Name ', 'Year'],
      dtype='object')

In [193]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Segment                700 non-null    object
 1   Country                700 non-null    object
 2    Product               700 non-null    object
 3    Discount Band         700 non-null    object
 4    Units Sold            700 non-null    object
 5    Manufacturing Price   700 non-null    object
 6    Sale Price            700 non-null    object
 7    Gross Sales           700 non-null    object
 8    Discounts             700 non-null    object
 9     Sales                700 non-null    object
 10   COGS                  700 non-null    object
 11   Profit                700 non-null    object
 12  Date                   700 non-null    object
 13  Month Number           700 non-null    int64
 14   Month Name            700 non-null    object
 15  Year                   700 non-null    int64
dtypes: int64(2), object(14)
memory usage: 87.6+ KB

In [194]:
df.describe()

       Month Number         Year
count    700.000000   700.000000
mean       7.900000  2013.750000
std        3.377321     0.433322
min        1.000000  2013.000000
25%        5.750000  2013.750000
50%        9.000000  2014.000000
75%       10.250000  2014.000000
max       12.000000  2014.000000

In [195]:
df.isnull().sum()

Segment                  0
Country                  0
 Product                 0
 Discount Band           0
 Units Sold              0
 Manufacturing Price     0
 Sale Price              0
 Gross Sales             0
 Discounts               0
  Sales                  0
 COGS                    0
 Profit                  0
Date                     0
Month Number             0
 Month Name              0
Year                     0
dtype: int64

In [196]:
df.shape

(700, 16)

In [197]:
df.tail()

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
695,Small Business,France,Amarilla,High,"$2,475.00",$260.00,$300.00,"$7,42,500.00","$1,11,375.00","$6,31,125.00","$6,18,750.00","$12,375.00",01/03/2014,3,March,2014
696,Small Business,Mexico,Amarilla,High,$546.00,$260.00,$300.00,"$1,63,800.00","$24,570.00","$1,39,230.00","$1,36,500.00","$2,730.00",01/10/2014,10,October,2014
697,Government,Mexico,Montana,High,"$1,368.00",$5.00,$7.00,"$9,576.00","$1,436.40","$8,139.60","$6,840.00","$1,299.60",01/02/2014,2,February,2014
698,Government,Canada,Paseo,High,$723.00,$10.00,$7.00,"$5,061.00",$759.15,"$4,301.85","$3,615.00",$686.85,01/04/2014,4,April,2014
699,Channel Partners,United States of America,VTT,High,"$1,806.00",$250.00,$12.00,"$21,672.00","$3,250.80","$18,421.20","$5,418.00","$13,003.20",01/05/2014,5,May,2014

# Tratamento de Dados


1.   Limpeza de colunas financeiras
2.  Conversão de dados de colunas
1. Criação de novas colunas

##Parte 1 - Limpeza de colunas financeiras

In [198]:
#Verificando dados do Dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 16 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Segment                700 non-null    object
 1   Country                700 non-null    object
 2    Product               700 non-null    object
 3    Discount Band         700 non-null    object
 4    Units Sold            700 non-null    object
 5    Manufacturing Price   700 non-null    object
 6    Sale Price            700 non-null    object
 7    Gross Sales           700 non-null    object
 8    Discounts             700 non-null    object
 9     Sales                700 non-null    object
 10   COGS                  700 non-null    object
 11   Profit                700 non-null    object
 12  Date                   700 non-null    object
 13  Month Number           700 non-null    int64
 14   Month Name            700 non-null    object
 15  Year                   700 non-null    int64
dtypes: int64(2), object(14)
memory usage: 87.6+ KB

In [199]:
#Verificando dados nulos do Dataset
df.isnull().sum()

Segment                  0
Country                  0
 Product                 0
 Discount Band           0
 Units Sold              0
 Manufacturing Price     0
 Sale Price              0
 Gross Sales             0
 Discounts               0
  Sales                  0
 COGS                    0
 Profit                  0
Date                     0
Month Number             0
 Month Name              0
Year                     0
dtype: int64

In [200]:
#Verificando dados do Dataset
df.describe()

       Month Number         Year
count    700.000000   700.000000
mean       7.900000  2013.750000
std        3.377321     0.433322
min        1.000000  2013.000000
25%        5.750000  2013.750000
50%        9.000000  2014.000000
75%       10.250000  2014.000000
max       12.000000  2014.000000

In [201]:
#Removendo espaços extras dos nomes das colunas
df.columns = df.columns.str.strip().str.replace(' ', '_')

In [202]:
#Verificando se os espaços foram removidos
df.columns

Index(['Segment', 'Country', 'Product', 'Discount_Band', 'Units_Sold',
       'Manufacturing_Price', 'Sale_Price', 'Gross_Sales', 'Discounts',
       'Sales', 'COGS', 'Profit', 'Date', 'Month_Number', 'Month_Name',
       'Year'],
      dtype='object')

In [203]:
#Removendo símbolos de colunas monetárias
colunas_monetarias = ['Units_Sold','Manufacturing_Price','Sale_Price','Gross_Sales','Discounts','Sales','COGS','Profit']

for col in colunas_monetarias:
    df[col] = df[col].replace({'\$': '', ',': ''}, regex=True)

<>:5: SyntaxWarning: invalid escape sequence '\$'
<>:5: SyntaxWarning: invalid escape sequence '\$'
/tmp/ipykernel_1145/3331062191.py:5: SyntaxWarning: invalid escape sequence '\$'
  df[col] = df[col].replace({'\$': '', ',': ''}, regex=True)

In [204]:
#Conferindo a remoção dos símbolos
df.head()

,Segment,Country,Product,Discount_Band,Units_Sold,Manufacturing_Price,Sale_Price,Gross_Sales,Discounts,Sales,COGS,Profit,Date,Month_Number,Month_Name,Year
0,Government,Canada,Carretera,None,1618.50,3.00,20.00,32370.00,-,32370.00,16185.00,16185.00,01/01/2014,1,January,2014
1,Government,Germany,Carretera,None,1321.00,3.00,20.00,26420.00,-,26420.00,13210.00,13210.00,01/01/2014,1,January,2014
2,Midmarket,France,Carretera,None,2178.00,3.00,15.00,32670.00,-,32670.00,21780.00,10890.00,01/06/2014,6,June,2014
3,Midmarket,Germany,Carretera,None,888.00,3.00,15.00,13320.00,-,13320.00,8880.00,4440.00,01/06/2014,6,June,2014
4,Midmarket,Mexico,Carretera,None,2470.00,3.00,15.00,37050.00,-,37050.00,24700.00,12350.00,01/06/2014,6,June,2014

In [205]:
#Verificando valores nulos
df.isnull().sum()

Segment                0
Country                0
Product                0
Discount_Band          0
Units_Sold             0
Manufacturing_Price    0
Sale_Price             0
Gross_Sales            0
Discounts              0
Sales                  0
COGS                   0
Profit                 0
Date                   0
Month_Number           0
Month_Name             0
Year                   0
dtype: int64

In [206]:
#Verificando a quantidade de valores únicos em cada coluna
df.nunique()

Segment                  5
Country                  5
Product                  6
Discount_Band            4
Units_Sold             510
Manufacturing_Price      6
Sale_Price               7
Gross_Sales            550
Discounts              515
Sales                  559
COGS                   545
Profit                 557
Date                    16
Month_Number            12
Month_Name              12
Year                     2
dtype: int64

In [207]:
#Transformando valores nulos representados por '-' em nan para que não influencie no andamento do projeto
import numpy as np

df['Discounts'] = df['Discounts'].str.strip()
df['Discounts'] = df['Discounts'].replace('-', np.nan)

In [208]:
#Verificando alteração de valores nulos na coluna 'Discounts'
df.head()

,Segment,Country,Product,Discount_Band,Units_Sold,Manufacturing_Price,Sale_Price,Gross_Sales,Discounts,Sales,COGS,Profit,Date,Month_Number,Month_Name,Year
0,Government,Canada,Carretera,None,1618.50,3.00,20.00,32370.00,NaN,32370.00,16185.00,16185.00,01/01/2014,1,January,2014
1,Government,Germany,Carretera,None,1321.00,3.00,20.00,26420.00,NaN,26420.00,13210.00,13210.00,01/01/2014,1,January,2014
2,Midmarket,France,Carretera,None,2178.00,3.00,15.00,32670.00,NaN,32670.00,21780.00,10890.00,01/06/2014,6,June,2014
3,Midmarket,Germany,Carretera,None,888.00,3.00,15.00,13320.00,NaN,13320.00,8880.00,4440.00,01/06/2014,6,June,2014
4,Midmarket,Mexico,Carretera,None,2470.00,3.00,15.00,37050.00,NaN,37050.00,24700.00,12350.00,01/06/2014,6,June,2014

##Parte 2 - Conversão de dados de colunas

In [209]:
import numpy as np

# Definindo uma função para limpar strings numéricas
def clean_numeric_string(value):
    if isinstance(value, str):
      # Remove todos os espaços
        value = value.strip().replace(' ', '')
        # TRansformando números com parênteses para números negativos: (X) -> -X
        if value.startswith('(') and value.endswith(')'):
            value = '-' + value[1:-1]
       # Removendo todos os caracteres não numéricos restantes, exceto o ponto decimal
        value = value.replace('$', '').replace(',', '')
        # Explicitamente tratando '-' como NaN após outras substituições
        if value == '-':
            return np.nan
        # Convertendo strings vazias em NaN
        if value == '':
            return np.nan
    return value

colunas = ['Units_Sold', 'Manufacturing_Price', 'Sale_Price', 'Gross_Sales', 'Discounts', 'Sales', 'COGS', 'Profit']

# Aplica a função de limpeza a cada coluna.
for col in colunas:
    df[col] = df[col].apply(clean_numeric_string)

# Converte as colunas limpas para o formato float.
df[colunas] = df[colunas].astype(float)

In [210]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Segment              700 non-null    object
 1   Country              700 non-null    object
 2   Product              700 non-null    object
 3   Discount_Band        700 non-null    object
 4   Units_Sold           700 non-null    float64
 5   Manufacturing_Price  700 non-null    float64
 6   Sale_Price           700 non-null    float64
 7   Gross_Sales          700 non-null    float64
 8   Discounts            647 non-null    float64
 9   Sales                700 non-null    float64
 10  COGS                 700 non-null    float64
 11  Profit               695 non-null    float64
 12  Date                 700 non-null    object
 13  Month_Number         700 non-null    int64
 14  Month_Name           700 non-null    object
 15  Year                 700 non-null    int64
dtypes: float64(8), int64(2), object(6)
memory usage: 87.6+ KB

In [211]:
#Verificando tipos de variáveis (colunas)
df.dtypes

Segment                 object
Country                 object
Product                 object
Discount_Band           object
Units_Sold             float64
Manufacturing_Price    float64
Sale_Price             float64
Gross_Sales            float64
Discounts              float64
Sales                  float64
COGS                   float64
Profit                 float64
Date                    object
Month_Number             int64
Month_Name              object
Year                     int64
dtype: object

In [212]:
#Alterando o tipo da coluna Date
df['Date'] = pd.to_datetime(df['Date'])

In [213]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Segment              700 non-null    object
 1   Country              700 non-null    object
 2   Product              700 non-null    object
 3   Discount_Band        700 non-null    object
 4   Units_Sold           700 non-null    float64
 5   Manufacturing_Price  700 non-null    float64
 6   Sale_Price           700 non-null    float64
 7   Gross_Sales          700 non-null    float64
 8   Discounts            647 non-null    float64
 9   Sales                700 non-null    float64
 10  COGS                 700 non-null    float64
 11  Profit               695 non-null    float64
 12  Date                 700 non-null    datetime64[ns]
 13  Month_Number         700 non-null    int64
 14  Month_Name           700 non-null    object
 15  Year                 700 non-null    int64
dtypes: datetime64[ns](1), float64(8), int64(2), object(5)
memory usage: 87.6+ KB

##Parte 3 - Criação de novas colunas

In [214]:
#Criando a coluna "MARGEM"
#Definindo a fórmula com objetivo de obter a margem de lucro.
#A divisão Profit / Sales calcula a proporção do lucro em relação à receita.
df['Margin'] = df['Profit'] / df['Sales'] *100

In [215]:
#Criando a coluna "TICKET MÉDIO POR UNIDADE"
#A divisão Sales / Units_Sold calcula o valor médio de cada unidade vendida quanto em média cada produto foi vendido.
df['Average_Ticket_Per_Unit'] = df['Sales'] / df['Units_Sold']

In [216]:
#Criando a coluna "ANO-MÊS(YYYY-MM)"
df['Year_Month'] = df['Date'].dt.strftime('%Y-%m') #,dt.strftime(('%Y-%m) formata cada data para o padrão ano-mês')

In [217]:
#Criando a coluna "INDICADOR DE DESCONTO (SIM=1/NÃO=0)"
#A função lambda verifica se a coluna Discounts possui valor maior que 0, se sim, preenche com Yes, Senão, Com No.
df['Discount_indicator'] = df['Discounts'].apply(lambda x: 'Yes' if x > 0 else 'No')

In [218]:
#Criando a coluna "PERCENTUAL DE DESCONTO"
#A divisão Discounts / Gross_Sales calcula a proporção do desconto em relação às vendas brutas.
df['Discount_percentage'] = (df['Discounts'] / df['Gross_Sales']) * 100

In [219]:
#Conferindo se as colunas foram criadas corretamente
df.head()

,Segment,Country,Product,Discount_Band,Units_Sold,Manufacturing_Price,Sale_Price,Gross_Sales,Discounts,Sales,...,Profit,Date,Month_Number,Month_Name,Year,Margin,Average_Ticket_Per_Unit,Year_Month,Discount_indicator,Discount_percentage
0,Government,Canada,Carretera,None,1618.5,3.0,20.0,32370.0,NaN,32370.0,...,16185.0,2014-01-01,1,January,2014,50.000000,20.0,2014-01,No,NaN
1,Government,Germany,Carretera,None,1321.0,3.0,20.0,26420.0,NaN,26420.0,...,13210.0,2014-01-01,1,January,2014,50.000000,20.0,2014-01,No,NaN
2,Midmarket,France,Carretera,None,2178.0,3.0,15.0,32670.0,NaN,32670.0,...,10890.0,2014-01-06,6,June,2014,33.333333,15.0,2014-01,No,NaN
3,Midmarket,Germany,Carretera,None,888.0,3.0,15.0,13320.0,NaN,13320.0,...,4440.0,2014-01-06,6,June,2014,33.333333,15.0,2014-01,No,NaN
4,Midmarket,Mexico,Carretera,None,2470.0,3.0,15.0,37050.0,NaN,37050.0,...,12350.0,2014-01-06,6,June,2014,33.333333,15.0,2014-01,No,NaN

In [220]:
#Renomeando a coluna "MARGEM"
df.rename(columns={'Margin (%)': 'Margin'}, inplace=True)

In [221]:
#Verificando todas as colunas existentes no Dataset
df.columns

Index(['Segment', 'Country', 'Product', 'Discount_Band', 'Units_Sold',
       'Manufacturing_Price', 'Sale_Price', 'Gross_Sales', 'Discounts',
       'Sales', 'COGS', 'Profit', 'Date', 'Month_Number', 'Month_Name', 'Year',
       'Margin', 'Average_Ticket_Per_Unit', 'Year_Month', 'Discount_indicator',
       'Discount_percentage'],
      dtype='object')

In [222]:
#Conferindo tipos de colunas
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Segment                  700 non-null    object
 1   Country                  700 non-null    object
 2   Product                  700 non-null    object
 3   Discount_Band            700 non-null    object
 4   Units_Sold               700 non-null    float64
 5   Manufacturing_Price      700 non-null    float64
 6   Sale_Price               700 non-null    float64
 7   Gross_Sales              700 non-null    float64
 8   Discounts                647 non-null    float64
 9   Sales                    700 non-null    float64
 10  COGS                     700 non-null    float64
 11  Profit                   695 non-null    float64
 12  Date                     700 non-null    datetime64[ns]
 13  Month_Number             700 non-null    int64
 14  Month_Name               700 non-null    object
 15  Year                     700 non-null    int64
 16  Margin                   695 non-null    float64
 17  Average_Ticket_Per_Unit  700 non-null    float64
 18  Year_Month               700 non-null    object
 19  Discount_indicator       700 non-null    object
 20  Discount_percentage      647 non-null    float64
dtypes: datetime64[ns](1), float64(11), int64(2), object(7)
memory usage: 115.0+ KB

In [223]:
#Verificando colunas
df.columns

Index(['Segment', 'Country', 'Product', 'Discount_Band', 'Units_Sold',
       'Manufacturing_Price', 'Sale_Price', 'Gross_Sales', 'Discounts',
       'Sales', 'COGS', 'Profit', 'Date', 'Month_Number', 'Month_Name', 'Year',
       'Margin', 'Average_Ticket_Per_Unit', 'Year_Month', 'Discount_indicator',
       'Discount_percentage'],
      dtype='object')

# Fim do Checkpoint da semana 01

In [224]:
#Conferindo tamanho final do Dataset (700 linhas, 21 colunas)
df.shape

(700, 21)

In [225]:
# ==============================
# VERIFICAÇÃO FINAL DO DATASET
# ==============================

# verificar estrutura
df.info()

# verificar valores nulos
print("\nValores nulos por coluna:")
print(df.isnull().sum())

# verificar duplicatas
print("\nLinhas duplicadas:", df.duplicated().sum())

# estatísticas das colunas numéricas
print("\nEstatísticas gerais:")
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Segment                  700 non-null    object
 1   Country                  700 non-null    object
 2   Product                  700 non-null    object
 3   Discount_Band            700 non-null    object
 4   Units_Sold               700 non-null    float64
 5   Manufacturing_Price      700 non-null    float64
 6   Sale_Price               700 non-null    float64
 7   Gross_Sales              700 non-null    float64
 8   Discounts                647 non-null    float64
 9   Sales                    700 non-null    float64
 10  COGS                     700 non-null    float64
 11  Profit                   695 non-null    float64
 12  Date                     700 non-null    datetime64[ns]
 13  Month_Number             700 non-null    int64
 14  Month_Name               700 non-null    object
 15  Year                     700 non-null    int64
 16  Margin                   695 non-null    float64
 17  Average_Ticket_Per_Unit  700 non-null    float64
 18  Year_Month               700 non-null    object
 19  Discount_indicator       700 non-null    object
 20  Discount_percentage      647 non-null    float64
dtypes: datetime64[ns](1), float64(11), int64(2), object(7)
memory usage: 115.0+ KB

Valores nulos por coluna:
Segment                     0
Country                     0
Product                     0
Discount_Band               0
Units_Sold                  0
Manufacturing_Price         0
Sale_Price                  0
Gross_Sales                 0
Discounts                  53
Sales                       0
COGS                        0
Profit                      5
Date                        0
Month_Number                0
Month_Name                  0
Year                        0
Margin                      5
Average_Ticket_Per_Unit     0
Year_Month                  0
Discount_indicator          0
Discount_percentage        53
dtype: int64

Linhas duplicadas: 0

Estatísticas gerais:
        Units_Sold  Manufacturing_Price  Sale_Price   Gross_Sales  \
count   700.000000           700.000000  700.000000  7.000000e+02
mean   1608.294286            96.477143  118.428571  1.827594e+05
min     200.000000             3.000000    7.000000  1.799000e+03
25%     905.000000             5.000000   12.000000  1.739175e+04
50%    1542.500000            10.000000   20.000000  3.798000e+04
75%    2229.125000           250.000000  300.000000  2.790250e+05
max    4492.500000           260.000000  350.000000  1.207500e+06
std     867.427859           108.602612  136.775515  2.542623e+05

           Discounts         Sales           COGS         Profit  \
count     647.000000  7.000000e+02     700.000000     695.000000
mean    14227.586198  1.696091e+05  145475.211429   24307.485309
min        18.410000  1.655080e+03     918.000000  -40617.500000
25%      1061.000000  1.592800e+04    7490.000000    2929.320000
50%      3108.000000  3.554020e+04   22506.250000    9297.000000
75%     18809.250000  2.610775e+05  245607.500000   22777.500000
max    149677.500000  1.159200e+06  950625.000000  262200.000000
std     23562.833079  2.367263e+05  203865.506118   42865.115657

                      Date  Month_Number         Year      Margin  \
count                  700    700.000000   700.000000  695.000000
mean   2013-10-08 15:36:00      7.900000  2013.750000   28.101683
min    2013-01-09 00:00:00      1.000000  2013.000000  -12.941176
25%    2013-10-04 12:00:00      5.750000  2013.750000   13.194444
50%    2014-01-05 12:00:00      9.000000  2014.000000   23.371648
75%    2014-01-09 06:00:00     10.250000  2014.000000   43.501021
max    2014-01-12 00:00:00     12.000000  2014.000000   75.000000
std                    NaN      3.377321     0.433322   23.382643

       Average_Ticket_Per_Unit  Discount_percentage
count               700.000000           647.000000
mean                109.800943             7.933540
min                   5.950000             1.000000
25%                  11.760000             5.000000
50%                  18.400000             8.000000
75%                 267.750000            12.000000
max                 350.000000            15.000000
std                 126.958731             4.259781

In [226]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Segment                  700 non-null    object
 1   Country                  700 non-null    object
 2   Product                  700 non-null    object
 3   Discount_Band            700 non-null    object
 4   Units_Sold               700 non-null    float64
 5   Manufacturing_Price      700 non-null    float64
 6   Sale_Price               700 non-null    float64
 7   Gross_Sales              700 non-null    float64
 8   Discounts                647 non-null    float64
 9   Sales                    700 non-null    float64
 10  COGS                     700 non-null    float64
 11  Profit                   695 non-null    float64
 12  Date                     700 non-null    datetime64[ns]
 13  Month_Number             700 non-null    int64
 14  Month_Name               700 non-null    object
 15  Year                     700 non-null    int64
 16  Margin                   695 non-null    float64
 17  Average_Ticket_Per_Unit  700 non-null    float64
 18  Year_Month               700 non-null    object
 19  Discount_indicator       700 non-null    object
 20  Discount_percentage      647 non-null    float64
dtypes: datetime64[ns](1), float64(11), int64(2), object(7)
memory usage: 115.0+ KB

In [228]:
# ==============================
# EXPORTAR DATASET TRATADO
# ==============================
df.to_csv('/content/drive/MyDrive/Projeto-analise-vendas/data/dataset_tratado_v6.csv', index=False)
print("Dataset tratado salvo com sucesso no Google Drive.")

Dataset tratado salvo com sucesso no Google Drive.